# Build settings

markdown: kramdown
permalink: pretty

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

baseurl: '/Winter-Portfolio-2016'
url: "https://gazitaufiqislam.github.io/Winter-Portfolio-2016"
